{% set name = "alsa-plugins" %}
{% set version = "1.2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alsa-project/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6cee24859ed3575ab3534471bbb4489f6fa9816f31ea85fe968f77bc57296522

build:
  number: 10
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf
    - automake
    - libtool
    - make
    - pkg-config
  host:
    # unversioned dep on alsa-lib to get conda-forge pin
    - alsa-lib
    # alsa-plugins needs an alsa-lib with a version >= to its own
    - alsa-lib >={{ version }}
    - ffmpeg
    - jack
    - pulseaudio

test:
  commands:
    {% set mods = ["conf_pulse", "ctl_arcam_av", "ctl_oss", "ctl_pulse"] %}
    {% set mods = mods + ["pcm_a52", "pcm_jack", "pcm_oss", "pcm_pulse"] %}
    {% set mods = mods + ["pcm_upmix", "pcm_usb_stream", "pcm_vdownmix"] %}
    {% set mods = mods + ["rate_lavrate", "rate_lavrate_fast", "rate_lavrate_faster"] %}
    {% set mods = mods + ["rate_lavrate_high", "rate_lavrate_higher", "rate_speexrate"] %}
    {% set mods = mods + ["rate_speexrate_best", "rate_speexrate_medium"] %}
    {% for mod in mods %}
    - test -f $PREFIX/lib/alsa-lib/libasound_module_{{ mod }}$SHLIB_EXT
    {% endfor %}

about:
  home: http://www.alsa-project.org/main/index.php/Main_Page
  license: LGPL-2.1-or-later AND GPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.GPL
  summary: The Advanced Linux Sound Architecture (ALSA) - plugins
  description: |
    Plugins for the ALSA library, including play or capture via JACK or Pulse Audio and
    stream conversions.
  dev_url: https://github.com/alsa-project/alsa-plugins

extra:
  recipe-maintainers:
    - ryanvolz
